const { AttachmentBuilder, EmbedBuilder } = require('discord.js');
const customEmbed = require('../../components/CustomEmbed');

module.exports = {
    name: 'embed',
    description: 'embed',
    devOnly: false,
    //testOnly: Boolean,
    //options: Object[],
    //deleted: false,

    callback: (client, interaction) => {

        const { embed, files } = customEmbed("Test Embed", "This is a test embed generated by the CustomEmbedBuilder");

        interaction.reply({
            embeds: [embed],
            files: files,
            ephemeral: true,
        });
        
    },
}